### ISSUE TITLE
hey flame

### ISSUE THREAD

**Issue by thaidzdzdz** [Lvl9999/FlamesW#3]
i love you so much how to i pay for ps crack you say i am going to make it so worth it in the future I NEED IT SLIDE LINK

**Comment by kriinios** [comment]
fuck you nigger

**Comment by kriinios** [comment]
thaidzdz is an annoying nigger only flames is a W

**Comment by sashamaners15** [comment]
hi

**Comment by Lvl9999** [comment]
oil up

**Comment by sashamaners15** [comment]
https://www.roblox.com/users/203045121/profile follow pls

**Comment by kriinios** [comment]
shut up all of you niggers except mommy flame

**Comment by sashamaners15** [comment]
![imgonline-com-ua-convertiJWuRCavUR1l](https://github.com/user-attachments/assets/1a994fc8-0e34-4b17-ba0a-29a08884ae90)

**Comment by Lvl9999** [comment]
sasha?

**Comment by Lvl9999** [comment]
oil up
